version: '2'
services: 
        prometheus:
                image: "prom/prometheus"
                volumes:
                        - /home/manu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
                ports:
                        - "9090:9090"
        elasticDb:
                image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
                environment:
                        - "discovery.type=single-node"
                volumes:
                        - esdata1:/elasticData
                ports:
                        - "9200:9200"
                        - "9300:9300"


volumes:
        esdata1:
                driver: local
